/* tslint:disable */
/* eslint-disable */
/**
 * MongoDB Atlas Data API
 * A fully-managed API to read, write, and aggregate data in MongoDB Atlas. The Data API is powered by serverless Atlas Functions and secured with user authentication and role-based permissions. To learn more about the Data API, see [Atlas Data API](https://www.mongodb.com/docs/atlas/app-services/data-api/).  ## Set Up the Data API  Before you can use the Data API, you must enable and configure it in an Atlas App Services App. The configuration controls how the App\'s users authenticate, authorize requests, and interact with the API.  To learn how to start using the Data API in your App, see [Set up the Data API](https://www.mongodb.com/docs/atlas/app-services/data-api/generated-endpoints/#set-up-the-data-api).  ## Authenticate Requests  Your Data API configuration in App Services controls how users authenticate their API requests. In most cases, you will use Application authentication, which lets users log in with one of the App\'s authentication providers. Users can either provide their login credentials directly in every request or provide a reusable access token for an authenticated session.  To learn more, see [Authenticate Data API Requests](https://www.mongodb.com/docs/atlas/app-services/data-api/authenticate/).
 *
 * The version of the OpenAPI document: v1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from "../runtime";
/**
 *
 * @export
 * @interface FindManyRequestBody
 */
export interface FindManyRequestBody {
  /**
   * The name of a linked MongoDB Atlas data source. This is
   * commonly `"mongodb-atlas"` though it may be different in
   * your App if you chose a different name when you created the
   * data source.
   *
   * @type {string}
   * @memberof FindManyRequestBody
   */
  dataSource?: string;
  /**
   * The name of a database in the specified data source.
   * @type {string}
   * @memberof FindManyRequestBody
   */
  database?: string;
  /**
   * The name of a collection in the specified database.
   * @type {string}
   * @memberof FindManyRequestBody
   */
  collection?: string;
  /**
   * A MongoDB query filter that matches documents. For a list of all query operators that the Data API supports, see [Query Operators](https://www.mongodb.com/docs/atlas/app-services/mongodb/crud-and-aggregation-apis/#query-operators).
   * @type {object}
   * @memberof FindManyRequestBody
   */
  filter: object;
  /**
   * A [MongoDB projection](https://www.mongodb.com/docs/manual/tutorial/project-fields-from-query-results/) for matched documents returned by the operation.
   * @type {{ [key: string]: any; }}
   * @memberof FindManyRequestBody
   */
  projection?: { [key: string]: any };
  /**
   * A [MongoDB sort expression](https://www.mongodb.com/docs/manual/reference/method/cursor.sort/) that indicates sorted field names and directions.
   * @type {object}
   * @memberof FindManyRequestBody
   */
  sort?: object;
  /**
   * The maximum number of matching documents to include the in the response.
   * @type {number}
   * @memberof FindManyRequestBody
   */
  limit?: number;
  /**
   * The number of matching documents to omit from the response.
   * @type {number}
   * @memberof FindManyRequestBody
   */
  skip?: number;
}

/**
 * Check if a given object implements the FindManyRequestBody interface.
 */
export function instanceOfFindManyRequestBody(value: object): boolean {
  if (!("dataSource" in value)) return false;
  if (!("database" in value)) return false;
  if (!("collection" in value)) return false;
  if (!("filter" in value)) return false;
  return true;
}

export function FindManyRequestBodyFromJSON(json: any): FindManyRequestBody {
  return FindManyRequestBodyFromJSONTyped(json, false);
}

export function FindManyRequestBodyFromJSONTyped(
  json: any,
  ignoreDiscriminator: boolean
): FindManyRequestBody {
  if (json == null) {
    return json;
  }
  return {
    dataSource: json["dataSource"],
    database: json["database"],
    collection: json["collection"],
    filter: json["filter"],
    projection: json["projection"] == null ? undefined : json["projection"],
    sort: json["sort"] == null ? undefined : json["sort"],
    limit: json["limit"] == null ? undefined : json["limit"],
    skip: json["skip"] == null ? undefined : json["skip"],
  };
}

export function FindManyRequestBodyToJSON(
  value?: FindManyRequestBody | null
): any {
  if (value == null) {
    return value;
  }
  return {
    dataSource: value["dataSource"],
    database: value["database"],
    collection: value["collection"],
    filter: value["filter"],
    projection: value["projection"],
    sort: value["sort"],
    limit: value["limit"],
    skip: value["skip"],
  };
}
